set number
set relativenumber
set mouse=a
colorscheme panda
hi Normal guibg=NONE ctermbg=NONE
syntax on
set tabstop=4
set wildmenu
set wildmode=list:longest,full
set signcolumn=no
call plug#begin('~/.vim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
call plug#end()
