## Colors configuration
colors:
  # Default colors
  primary:
    background: '#131519'
    foreground: '#d8d8d8'

  # Normal colors
  normal:
    black:   '#27292D'
    red:     '#ec7875'
    green:   '#61c766'
    yellow:  '#fdd835'
    blue:    '#42a5f5'
    magenta: '#ba68c8'
    cyan:    '#4dd0e1'
    white:   '#d8d8d8'

  # Bright colors
  bright:
    black:   '#3B3D41'
    red:     '#fb8784'
    green:   '#70d675'
    yellow:  '#ffe744'
    blue:    '#51b4ff'
    magenta: '#c979d7'
    cyan:    '#5cdff0'
    white:   '#fdf6e3'
